### ISSUE TITLE
Whether these features are supported?

### ISSUE THREAD

**Issue by fengqi2019** [CCExtractor/rusty_ffmpeg#49]
i have two question about this crate:

can run on armv7?
rtsp convert to rtmp?just like:
ffmpeg -r 25 -i "rtsp://admin:admin@192.168.50.166:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif" -vcodec libx264 -r 25 -tune zerolatency -preset ultrafast -b:v 400k -vf 'scale=320:240' -f flv rtmp://106.52.214.221:1935/live/b827eb4dabbe0457020200209230404

thanks!

**Comment by ldm0** [comment]
1. FFmpeg can be compiled on armv7, and also Rust has armv7 support: [link](https://doc.rust-lang.org/nightly/rustc/platform-support.html), so you can run the example on armv7.

2, This crate is Rust bindings to FFmpeg inner libraries rather than an application. So no rtsp to rtmp convertion support.
